logging:
  file:
    name: C:/springcloudtraining/temp/spring-boot-elk.log
server:
  port: 8902

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

spring:
  application:
    name: ProductService

  data:
    mongodb:
      host: localhost
      port: 27017
      database: productdb

  zipkin:
    base-url: http://localhost:9411/

    sleuth:
      sampler:
        probability: 1 #100% (default = 10%)



    

  
